name: Data Structures and Algorithms Practice

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    
    - name: Upgrade pip
      run: |
        pip install --upgrade pip

    - name: Install Requirements
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest -v tests
      working-directory: ${{ github.workspace }}